disabled_rules:
- trailing_whitespace
- unused_closure_parameter
- unused_optional_binding
- force_cast
- redundant_string_enum_value

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 350
    error: 400
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 200
    error: 300

function_parameter_count:
    warning: 12
    error: 12

type_body_length:
    warning: 200
    error: 300

file_length:
    warning: 400
    error: 500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1

reporter: "xcode"

